united-build: 
language: generic
sudo: required
services:
- docker
script:
- travis_wait 33 && docker run -v $(pwd)/33:/root/enjoy/ --privileged=true --cap-add=ALL --security-opt seccomp:unconfined davidva/unibuild-33 /bin/sh -c "rm -f urpms && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x urpms && /urpms -g UnitedRPMs/libva-intel-driver -s libva-intel-driver.spec -t unitedrpms-33-i386 -c true"
notifications:
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bbc656ea277114ba4fd
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

